src/commands/briefcaseCommand.ts, src/commands/templateChooserCommand.ts, src/extension.ts, src/webviews.ts
~~Initially opening this as a draft because I don't know whether or not we want to change the behavior.~~ But per previous discussions, this would Promise-ify `InstructionsWebviewProvider.showDismissableInstructions()`, so that you could wait until the user had dismissed the instructions view, before moving on to the next stage.
=> Wait for dismissable instructions to be dismissed, before moving on

.github/workflows/create_release.yml, RELEASE.md, package-lock.json, package.json
First step to publishing! This creates a GitHub Action that will be manually triggered from the Actions tab. When run, this action will create a GitHub release on the repo, based on the package version in `package.json`. It will then build the VSIX package, and attach that package to the release as an artifact.
=> GHA to create a release

RELEASE.md, package.json
The size of the bundle doesn't change, and doing the dev pruning is otherwise breaking `vsce` when installed as a dev dependency.
Let's save the file culling for when we optimize the package.
=> Pruning dev is breaking vsce packaging

.github/workflows/create_release.yml, .github/workflows/publish_release.yml
I haven't been able to test the final (publishing) step, for obvious reasons. But I've tested the rest, by substituting the final step with a step that unzips the downloaded package and lists its contents, ensuring that we are in fact downloading a valid package from our release.
=> GHA to publish VSIX package

.github/workflows/publish_release.yml
I noticed in the publish flow that `npx vsce publish` downloaded and installed `vsce` (and complained about not using its full package name), because we weren't installing the package dependencies of the project.
=> Install package, to use vsce dependency for publish

package-lock.json, package.json
Volta does not support version ranges on pinning, so using Volta with the previous `>=18` version was actually breaking for Volta installations.
Moved our Node engine minimum version to the `engines` configuration, and pinned Node 18 for Volta at the latest version.
=> Fixing Node engine, Volta versions

resources/instructions/createSObjectLwcQuickActions.html, resources/instructions/landingPageTemplateChoice.html, src/commands/lwcGenerationCommand.ts, src/commands/wizard/landingPageCommand.ts, src/commands/wizard/lwcGenerationCommand.ts, src/commands/wizard/onboardingWizard.ts, src/commands/wizard/templateChooserCommand.ts, src/test/TestHelper.ts, src/test/suite/commands/wizard/landingPageCommand.test.ts, src/test/suite/commands/wizard/templateChooserCommand.test.ts, src/test/suite/utils/orgUtils.test.ts, src/test/suite/webviews.test.ts, src/webviews/processor.ts
Allows the user to choose their landing page from one of the templates in the Offline Starter Kit project.
=> Choose landing page from templates

resources/templates/createRecord/createRecord.css, resources/templates/createRecord/createRecord.html, resources/templates/createRecord/createRecord.js, resources/templates/createRecord/createRecord.js-meta.xml, resources/templates/editRecord/editRecord.css, resources/templates/editRecord/editRecord.html, resources/templates/editRecord/editRecord.js, resources/templates/editRecord/editRecord.js-meta.xml, resources/templates/viewRecord/viewRecord.css, resources/templates/viewRecord/viewRecord.html, resources/templates/viewRecord/viewRecord.js, resources/templates/viewRecord/viewRecord.js-meta.xml
For team discussion.
This is what I was thinking for "template files". Basically just placeholders in the file for the following variables we would need to programmatically substitute when generating the files. There's tons of possibilities, but this seems the simplest that I can think of.
VIEW TEMPLATE:
TEMPLATE_IMPORTS - actual imports from the @salesforce/schema namespace.
TEMPLATE_FIELDS - comma separated name of imported fields, ie NAME_FIELD, ACCOUNT_FIELD, etc
TEMPLATE_VIEW_LWC_LABEL - label for the view lwc
TEMPLATE_OBJECT_API_NAME
EDIT TEMPLATE:
TEMPLATE_LIGHTNING_INPUT_EDIT_FIELDS_HTML
<lightning-input-field field-name={nameField}></lightning-input-field>
TEMPLATE_OBJECT_API_NAME
TEMPLATE_VARIABLES
nameField = NAME_FIELD;
TEMPLATE_EDIT_LWC_LABEL - label for the edit lwc
CREATE …
=> Initial pass at templates for each LWC.

resources/instructions/createSObjectLwcQuickActions.html, src/commands/wizard/lwcGenerationCommand.ts, src/test/suite/commands/wizard/lwcGenerationCommand.test.ts
May require some tweaking during integration, but this should be a good stepping stone.
@sfdctaka @khawkins @maliroteh-sf
=> Checks for a list of sobjects and the corresponding create/edit/view qa directories.

src/commands/wizard/lwcGenerationCommand.ts, src/test/suite/utils/orgUtils.test.ts, src/utils/orgUtils.ts
To get a compact layout for a sObject I am using 2-pass process.
If sObject has compact layout assigned it will have `defaultCompactLayoutId` assigned. Otherwise, `null` is assigned and in that case the compact layout is defaults to `SYSTEM` compact layout.
After determining which compact layout is actually needed only after that a second network request need to be made in order to get the actual layout content.
=> Get correct compact layout for sObject

resources/instructions/createSObjectLwcQuickActions.html, resources/templates/quickAction.xml, src/commands/wizard/lwcGenerationCommand.ts, src/commands/wizard/onboardingWizard.ts, src/test/suite/utils/codeBuilder.test.ts, src/test/suite/utils/orgUtils.test.ts, src/utils/codeBuilder.ts, src/utils/orgUtils.ts, src/utils/workspaceUtils.ts
=> Now able to generate LWCs using template files.

package.json, src/commands/wizard/deployToOrgCommand.ts, src/extension.ts, src/services/CoreExtensionService.ts, src/services/index.ts, src/test/TestHelper.ts, src/test/runTest.ts, src/test/suite/commands/wizard/lwcGenerationCommand.test.ts, src/test/suite/utils/orgUtils.test.ts, src/test/suite/utils/uiUtils.test.ts, src/test/suite/utils/workspaceUtils.test.ts, src/types/AuthFields.ts, src/types/CoreExtensionApi.ts, src/types/SingleRecordQueryOptions.ts, src/types/WorkspaceContext.ts, src/types/index.ts, src/utils/constants.ts, src/utils/orgUtils.ts
This PR tacks to a design pattern recommended by the Salesforce Extensions team, for consuming the services that their extension exports for Org-based administration, connections, etc. With the previous implementation, we weren't successfully able to bootstrap a connection to the user's default Org, for retrieving sObject metadata.
=> Getting Org connection from Salesforce Extensions services

package-lock.json, src/test/runTest.ts
[Sounds like](https://github.com/microsoft/vscode/issues/200895#issuecomment-1857280064) a bump in the `@vscode/test-electron` dependency may fix the Windows test issue we saw in https://github.com/salesforce/salesforcedx-vscode-mobile/pull/57. Giving it a whirl.
=> Attempting to patch VSCode tests issue

src/commands/wizard/templateChooserCommand.ts, src/test/suite/commands/wizard/templateChooserCommand.test.ts
Fixing flapping tests.
Looks like the async() approach was causing a sporadic failure, due to askUserToOverwriteLandingPage() not being stubbed.
@khawkins @maliroteh-sf @sfdctaka
=> Handling undefined case like a "No" selection.

resources/instructions/createSObjectLwcQuickActions.html, src/commands/wizard/lwcGenerationCommand.ts, src/test/suite/commands/wizard/lwcGenerationCommand.test.ts
@khawkins @maliroteh-sf @sfdctaka
=> Handle case where an error occurs of any type when attempting to get page layout for missing objects.

.github/workflows/publish_release.yml, package-lock.json, package.json
Does what it says on the tin. Not sure if we want to also bump the patch version and publish a release for these changes or not? But otherwise, hopefully the updates are fairly self explanatory. Open VSX publishing implemented per their [documentation](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).
=> Additionally publish to Open VSX

.vscode/settings.json, src/test/runTest.ts
Just helps keep VSCode formatting synced up with what we align to in our Node project.
=> Telling VSCode that Prettier is the default formatter

.vscode/settings.json, src/commands/wizard/authorizeCommand.ts, src/commands/wizard/deployToOrgCommand.ts, src/test/runTest.ts
salesforcedx-vscode-core changed all sfdx.* command to sf.*. we need to match the change
=> fix: update sfdx command to sf to match dependent command id change

package.json, package.nls.json, src/commands/lint/configureLintingToolsCommand.ts, src/test/suite/commands/lint/configureLintingToolsCommand.test.ts
Scaffolding up adding lwc-mobile eslint plugin into salesforcedx-vscode-mobile.  
not fully read yet, need to wait for lwc-mobile eslint plugin release to npmjs.com
=> feat: config lwc mobile eslint plugin

package.json
The Salesforce logger looks for `transformStream` by using the relative path `../../lib/loggger/transformStream`.  This function belongs to @salesforce-core. The fix is to modify `bundle:extentions` and make the `salesforce-core` external to the generated `extension.js`
=> fix: re-authorization is needed even if the offline app is already authorized

lsp/server/src/test/validateGraphql.spec.ts, lsp/server/src/test/validateGraphql.test.ts, lsp/server/src/test/validateJs.test.ts, lsp/server/src/validateDocument.ts, lsp/server/src/validateGraphql.ts, lsp/server/src/validateJs.ts
Diagnostics count threshold was checked per validator. Also, similar code pattern of doing the math for calculating threshold was implicitly required for future validators to be added.
So instead, making validators do what they are made for. Validate. Checking for maximum count of diagnostic threshold is moved up to the caller. This makes code read simpler and validator to do it's single responsibility.
This change does not incur a hit in performance as diagnostics previously had always been queried for.
=> chore: simplify diagnostic counting

package.json
By always deleting tsconfig.tsbuildinfo ahead of `tsc` we force new builds for LSP client and server
=> Always delete tsconfig.tsbuildinfo

.github/dependabot.yml
Changes the dependabot configuration to group minor and patch dependency updates into one PR.
Cuts down on the noise of dependency update PRs.
=> Group minor and patch dependency updates together

lsp/client/src/extension.ts, lsp/server/src/diagnostic/js/adapters-local-change-not-aware.ts, lsp/server/src/server.ts, lsp/server/src/test/diagnostic/js/adapters-local-change-not-aware.test.ts, lsp/server/src/test/validator/graphqlValidator.test.ts, lsp/server/src/test/validator/htmlValidator.test.ts, lsp/server/src/test/validator/jsValidator.test.ts, lsp/server/src/test/validatorManager.test.ts, lsp/server/src/validator/baseValidator.ts, lsp/server/src/validatorManager.ts, package-lock.json
getRelatedListRecords is finalized to 
getRelatedListCount is finalized to
=> Finalize draft not aware Finalize draft not aware diagnostics for getRelatedListRecords and getRelatedListCount

.github/workflows/run-tests.yml, README.md, codecov.yml, test/suite/index.ts
Post nyc code coverage report to `https://app.codecov.io/`, which can be referenced by perf dashboard.
=> Coverage report posted to codecov

package-lock.json, package.json, scripts/copyComponentExperiencesYaml.js, scripts/copyResources.js, src/lsp/client/client.ts
Implemented feedback from last PR.
* Updated LanguageClient's ID.
* Use node script to determine the platform(Windows vs Unix) where it is running and run appropriate copy command.
=> LanguageClient ID. And, use node script to copy yaml file.

scripts/copyResources.js
Successively running commands `npm run compile` and then `npm run test` threw an error below. To handle this gracefully `mkdirSync` is called with an option so that an error won't be thrown if the directory exists.
```
Error: EEXIST: file already exists, mkdir '/Users/t.arai/Documents/codebase/salesforcedx-vscode-mobile/out/src/resources'
at Object.mkdirSync (node:fs:1371:26)
at Object.<anonymous> (/Users/t.arai/Documents/codebase/salesforcedx-vscode-mobile/scripts/copyResources.js:9:4)
at Module._compile (node:internal/modules/cjs/loader:1469:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at Module.load (node:internal/modules/cjs/loader:1288:32)
at Module._load (node:internal/modules/cjs/loader:1104:12)
at Function.executeUserEntryPoint [as runMain] …
```
=> mkdirSync can throw error

src/lsp/docs/adapters-local-change-not-aware.md, src/lsp/docs/over-sized-record.md
=> W-16620689 Add md files for [LWC Auth Debug] LSP to reduce OOM issues story

package-lock.json, package.json, src/commands/lint/configureLintingToolsCommand.ts, src/commands/settings/settings.ts, src/commands/wizard/onboardingWizard.ts, src/extension.ts, src/lsp/client/client.ts, src/lsp/server/diagnostics/DiagnosticProducer.ts, src/lsp/server/diagnostics/gql/over-sized-record.ts, src/lsp/server/diagnostics/html/mobileOfflineFriendly.ts, src/lsp/server/diagnostics/js/adapters-local-change-not-aware.ts, src/lsp/server/server.ts, src/lsp/server/validatorManager.ts, src/lsp/server/validators/baseValidator.ts, test/suite/lsp/server/diagnostics/DiagnosticProducer.test.ts, test/suite/lsp/server/diagnostics/gql/over-sized-record.test.ts, test/suite/lsp/server/diagnostics/js/adapters-local-change-not-aware.test.ts, test/suite/lsp/server/validatorManager.test.ts, test/suite/lsp/server/validators/graphqlValidator.test.ts, test/suite/lsp/server/validators/htmlValidator.test.ts, test/suite/lsp/server/validators/jsValidator.test.ts
Clive finished the md file writeup in [this merged pr](https://github.com/salesforce/salesforcedx-vscode-mobile/pull/165).  here we updated the code to point to the md file when diagnostic is rendered over mouse over.   
It looks like below and now it matches what eslint plugin reported problems for vscode now :)
=> Md file link for diagnostic
